apiVersion: v1
kind: Namespace
metadata:
  name: rstudio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio-server
  namespace: rstudio
spec:
  replicas: 1  # Only one replica as requested
  selector:
    matchLabels:
      app: rstudio-server
  template:
    metadata:
      labels:
        app: rstudio-server
    spec:
      containers:
      - name: rstudio-server
        image: guilhermelinsc/rstudio-ms:1.0
        ports:
        - containerPort: 8787
        resources:
          requests:
            cpu: "1000m"    # Request 1 vCPU
            memory: "1536Mi" # Request 1.5GiB of memory
          # No limits specified to allow vertical autoscaling
        volumeMounts:
        - mountPath: /home/rstudio
          name: rstudio-storage
      volumes:
      - name: rstudio-storage
        emptyDir:
          sizeLimit: 15Gi # Temporary storage with a limit
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: rstudio-vpa
  namespace: rstudio
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       rstudio-server
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: v1
kind: Service
metadata:
  name: rstudio-service
  namespace: rstudio
spec:
  type: LoadBalancer
  selector:
    app: rstudio-server
  ports:
  - port: 8787
    targetPort: 8787
    protocol: TCP
