name: GKE Deployment and Health Check

on:
  pull_request:
    branches: [main]

jobs:
  test-and-cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure gcloud & set GKE credentials
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet || true
          gcloud container clusters get-credentials test-iac-k8s-cluster \
            --zone us-east1 \
            --project GCP_PROJECT_ID

      - name: Deploy to GKE for testing
        run: |
          kubectl apply -f deploy/deployment.yml
          kubectl rollout status deployment/rstudio-deployment -n rstudio

      - name: HTTP health check
        run: |
          app_ip=$(kubectl get svc rstudio-deployment -n rstudio -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Testing http://$app_ip:8787"
          curl -fs "http://$app_ip:8787"

      - name: Clean up test deployment
        run: |
          kubectl delete -f deploy/deployment.yml

  gke-deploy:
    name: Deploy to GKE on Merge to Main
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure GKE
        run: |
          gcloud container clusters get-credentials test-iac-k8s-cluster \
            --zone us-east1 \
            --project GCP_PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl apply -f deploy/deployment.yml