name: GKE Deployment and Health Check

on:
  pull_request:
    branches: [main]

jobs:
  test-and-cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install GKE auth plugin
        run: |
          sudo apt update
          sudo apt install -y google-cloud-sdk-gke-gcloud-auth-plugin
        
      - name: Configure gcloud & set GKE credentials
        run: |
          gcloud container clusters get-credentials test-iac-k8s-cluster \
            --zone us-east1 \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE for testing
        run: |
          kubectl apply -f deploy/deployment.yml
          kubectl rollout status deployment/rstudio-deployment -n test-ns

      - name: HTTP health check
        run: |
          app_ip=$(kubectl get svc rstudio-deployment -n test-ns -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Waiting for http://$app_ip:8787"
          for i in {1..10}; do
            if curl -fs "http://$app_ip:8787"; then
              echo "Health check passed!"
              exit 0
            fi
            echo "Retrying in 5 seconds..."
            sleep 5
          done
          echo "Health check failed after retries"
          exit 1
      
      - name: Clean up test deployment
        run: |
          kubectl delete -f deploy/deployment.yml -n test-ns

  gke-deploy:
    name: Deploy to GKE on Merge to Main
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure GKE
        run: |
          gcloud container clusters get-credentials test-iac-k8s-cluster \
            --zone us-east1 \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f deploy/deployment.yml -n rstudio